export const HOME = '/home'
export const ADD_TRIP = '/home/add-trip'
export const ADD_ACTIVITY = '/home/add-activity'
export const FOOTPRINT_HISTORY = '/footprint-history'

export const WELCOME = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const PROFILE = '/profile'
export const PASSWORD_FORGET = '/pw-forget'
