export const lightTheme = {
  body: 'var(--woodland)',
  text: 'var(--sand)',
  textSecondary: 'var(--sand)',

  background: 'var(--woodland)',
  input: 'var(--sand)',
  inputColor: 'var(--dusk)',
  profileInputs: 'var(--orange-yellow)',
  inputDisabled: 'var(--sand)',
  textHighlight: 'var(--orange-yellow)',
  historyBackground: 'var(--sand)',
  radioButtonsText: 'var(--woodland)',
  radioButtonsChecked: 'var(--sunset)',
  donutChartLabels: 'var(--dusk)',
  logo: 'var(--woodland)',
  sectionHighlight: 'var(--orange-yellow)',
  headline: 'var(--sand)',
  link: 'var(--sand)',
  linkSelected: 'var(--seafoam)',
  sumCarbon: 'var(--sunset)',
  sumCarbonText: 'var(--sand)',
  backgroundProfileRelated: 'var(--sand)',
  textProfileRelated: '#091A1A',
  textError: '#FF8C66',
}

export const darkTheme = {
  body: 'var(--primaryBackground)',
  text: 'var(--primaryText)',
  textSecondary: 'var(--secondaryText)',
  background: 'var(--primaryBackground)',
  input: 'var(--greyFillColor)',
  inputColor: 'var(--secondaryText)',
  profileInputs: 'var(--greyFillColor)',
  inputDisabled: 'var(--primaryBackground)',
  textHighlight: 'var(--primaryVibrant)',
  historyBackground: 'var(--primaryBackground)',
  radioButtonsChecked: 'var(--primaryVibrant)',
  radioButtonsText: 'var(--textDark)',
  donutChartLabels: 'var(--dusk)',
  logo: 'var(--green)',
  sectionHighlight: 'var(--green)',
  headline: 'var(--textDark)',
  link: 'var(--textDark)',
  linkSelected: '#749dd6',
  sumCarbon: 'var(--red)',
  sumCarbonText: '#121212',
  backgroundProfileRelated: 'var(--primaryBackground)',
  textProfileRelated: 'var(--primaryText)',
  textError: 'var(--red)',
}
